# toggle for showing staff
show_staff: false

# collections
collections:
  authors:
    output: true

# layout setting
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 100
